name: Build and Install Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up repository and update
      run: |
        sudo add-apt-repository universe
        sudo apt update

    - name: Install dependencies
      run: |
        sudo apt install -y libffi-dev libssl-dev
        # Install libncurses6 as libncurses5 is not available
        sudo apt install -y libncurses6

    - name: Verify installation
      run: |
        dpkg -l | grep libffi-dev
        dpkg -l | grep libssl-dev
        dpkg -l | grep libncurses6
