name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip openjdk-11-jdk wget libz-dev
        pip install --upgrade pip setuptools
        pip install buildozer cython

    - name: Prepare environment for Buildozer
      run: |
        sudo apt install -y libffi-dev libssl-dev
        sudo apt install -y libncurses5 libstdc++6 lib32z1 libbz2-1.0
        sudo apt install -y libsqlite3-dev

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/
